const data = {
  SelectCourse: [
    {
      id: 1,
      img: "https://picsum.photos/500/300",
      url: "https://picsum.photos/500/300",
      title: "新手必學的3件事 - 進場點、停損點、停利點",
      special: 3200,
      text: " 一堂能讓各種交易風格都能更強大的衝刺課程！夠短，夠直接，能兼容在不同投資思維之中，能兼容在不同投資思維之中",
      star: 4,
      ratecount: 41,
      students: 752,
      videLength: 2.5,
      teacher: "王希律",
    },
    {
      id: 2,
      img: "https://picsum.photos/500/300",
      url: "https://picsum.photos/500/300",
      title: "新手必學的3件事 - 進場點、停損點、停利點",
      special: 3200,
      text: " 一堂能讓各種交易風格都能更強大的衝刺課程！夠短，夠直接，能兼容在不同投資思維之中，能兼容在不同投資思維之中",
      star: 3,
      ratecount: 41,
      students: 752,
      videLength: 2.5,
      teacher: "黃律",
    },
    {
      id: 3,
      img: "https://picsum.photos/500/300",
      url: "https://picsum.photos/500/300",
      title: "新手必學的3件事 - 進場點、停損點、停利點",
      special: 3200,
      text: " 一堂能讓各種交易風格都能更強大的衝刺課程！夠短，夠直接，能兼容在不同投資思維之中，能兼容在不同投資思維之中",
      star: 4,
      ratecount: 41,
      students: 752,
      videLength: 2.5,
      teacher: "王希律",
    },
    {
      id: 4,
      img: "https://picsum.photos/500/300",
      url: "https://picsum.photos/500/300",
      title: "新手必學的3件事 - 進場點、停損點、停利點",
      special: 3200,
      text: " 一堂能讓各種交易風格都能更強大的衝刺課程！夠短，夠直接，能兼容在不同投資思維之中，能兼容在不同投資思維之中",
      star: 4,
      ratecount: 41,
      students: 752,
      videLength: 2.5,
      teacher: "王希律",
    },
    {
      id: 5,
      img: "https://picsum.photos/500/300",
      url: "https://picsum.photos/500/300",
      title: "新手必學的3件事 - 進場點、停損點、停利點",
      special: 3200,
      text: " 一堂能讓各種交易風格都能更強大的衝刺課程！夠短，夠直接，能兼容在不同投資思維之中，能兼容在不同投資思維之中",
      star: 4,
      ratecount: 41,
      students: 752,
      videLength: 2.5,
      teacher: "王希律",
    },
    {
      id: 6,
      img: "https://picsum.photos/500/300",
      url: "https://picsum.photos/500/300",
      title: "新手必學的3件事 - 進場點、停損點、停利點",
      special: 3200,
      text: " 一堂能讓各種交易風格都能更強大的衝刺課程！夠短，夠直接，能兼容在不同投資思維之中，能兼容在不同投資思維之中",
      star: 4,
      ratecount: 41,
      students: 752,
      videLength: 2.5,
      teacher: "王希律",
    },
  ],
  seach: [
    {
      id: 1,
      title: "量價交易精髓：打造股票、期貨完美交易策略",
      time: "2023-01-02 15:15:30",
    },
  ],
};

export default data;